### ISSUE TITLE
Production values for erc721Rarible, erc721RaribleUser, erc1155Rarible, erc1155RaribleUser

### ISSUE THREAD

**Issue by winchell** [rarible/ethereum-indexer-public#177]
dev/staging application YAML have values for `erc721Rarible`, `erc721RaribleUser`, `erc1155Rarible`, `erc1155RaribleUser`, but not prod/mainnet. They aren't secrets, so can they be shared? I assume a two of them from https://etherscan.io/accounts/label/rarible but unsure about the `User` addresses.

`nft/listener/src/main/resources/config/application-dev.yml`:
```
common:
  royaltyRegistryAddress: "0x1747757768Ff4AA61390B1ed3AA019141605717B"
  factory:
    erc721Rarible: "0x2e6fAFAD2Af251Add7400cBD98C4620772692c49"
    erc721RaribleUser: "0xCc228ecb71B3456AeCb35D2dE66E228DAFd7Ae2d"
    erc1155Rarible: "0xbF90b7F8d59BE6D08dBd47fF984a22877996E91F"
    erc1155RaribleUser: "0x71Cf04F4f75eEb3262B1AB7D8438432EC4a30ee4"
```
